from .Asset.models import Assets
from .attendance.models import Attendance
from .audit.models import AuditLog
from .auth.models import User
from .department.models import Department
from .designation.models import Designation
from .document.models import Document
from .employee.models import Employee
from .leave.models import Leave
from .payroll.models import Payroll
from .role.models import Role
